### ISSUE TITLE
Updates are not available under Databox project

### ISSUE THREAD

**Issue by bafu** [me-box/databox-app#5]
Hi @ktg ,

Currently there are two places hosting Databox Android app:

* https://github.com/ktg/databox-app/
* https://github.com/me-box/databox-app/

The prior repository is updated by upstream, but the later one seems to be the official repository. Do you consider to merge them to one to prevent user from confusion?

**Comment by mor1** [comment]
@bafu Thanks for spotting this!

@ktg @Toshbrown @cgreenhalgh Could we resolve this please? 

I would suggest that we delete <https://github.com/me-box/databox-app/>, then @ktg transfers ownership of <https://github.com/ktg/databox-app/> to `me-box` org, and finally reforks to his own account (and remembers to push updates to upstream once they've been tested). Objections?

We would want to extract all the issues and, if possible, PRs before doing so, so that they could be pushed back up once @ktg repo moves.

**Comment by ktg** [comment]
I have brought this repository up to date, and deleted ktg/databox-app
